// scripts/generate-sudoku-puzzles.ts
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRng, generateSolvedBoard, removeCellsForUniqueSolution } from '../lib/sudoku-generator';

const POOL_SIZE = 200;
const TARGET_GIVENS = 32;

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '..', 'data', 'sudoku', 'puzzles.ts');

function toDigitString(board: number[]): string {
  return board.join('');
}

const puzzles: { givens: string; solution: string }[] = [];

for (let seed = 1; seed <= POOL_SIZE; seed++) {
  const solved = generateSolvedBoard(createRng(seed));
  // Offset the removal RNG's seed so it isn't correlated with the
  // generation RNG for the same puzzle index.
  const givens = removeCellsForUniqueSolution(solved, TARGET_GIVENS, createRng(seed + 1_000_000));
  puzzles.push({ givens: toDigitString(givens), solution: toDigitString(solved) });
}

const entries = puzzles.map((p) => `  { givens: '${p.givens}', solution: '${p.solution}' },`).join('\n');

const fileContent = `// Generated by \`npm run generate:sudoku\` — do not hand-edit.
// Each entry: an 81-character \`givens\` string (row-major, '0' = empty cell
// to fill in) and its 81-character \`solution\` string ('1'-'9' only).
export const SUDOKU_PUZZLES: { givens: string; solution: string }[] = [
${entries}
];
`;

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, fileContent);
console.log(`Wrote ${puzzles.length} puzzles to data/sudoku/puzzles.ts`);
